### ISSUE TITLE
Migrate blog builder from LFE Dragon to Clojure Dragon

### ISSUE THREAD

**Issue by oubiwann** [starship-hackers/blog#8]
* [x] Define org & artifact; reserve org name on Clojars
* [x] Restructure project for use with namespaces
* [x] Convert LFE to Clojure
* [x] Update data and page processing functions
* [x] Convert templates from ErlyDTL to Selmer
* [x] Convert static pages to generic markdown pages
* [x] Address post-conversions issues:
  * [x] Fix bad links:
     * [x] Update timeline links
     * [x] Either change github link or add link for starship-tools github org
  * [x] Fix bad content:
     * [x] Front page is not rendering headlines
     * [x] Front page headlines not showing darker background 
     * [x] Front page not showing site categories
     * [x] Category description is repeated on listing pages
     * [x] Post sidebar data missing timestamp
     * [x] Post sidebar missing social icons
     * [x] About pages no longer showing up
  * [ ] Fix bad CSS:
     * [x] Top-nav items are too close
     * [x] Top-nav "About" drop-down is unstyled
     * [x] "View older posts" on home page needs to be a button
     * [x] Post titles are not styled white
     * [x] Post subtitles are not styled white
     * [x] Post links are too dark -- almost can't read
     * [x] Post sidebar tags should not be bulleted list
     * [x] Post sidebar neighboring posts arrow icons not styled properly
     * [x] Post sidebar neighboring posts text not styled properly
     * [x] Post sidebar data items not styled properly

**Comment by oubiwann** [comment]
This work is being tracked in the following epic branch:
 * https://github.com/starship-tools/blog/tree/epic/8/lfe-to-clojure

**Comment by oubiwann** [comment]
Work is done; pending final testing and push of latest changes.
